apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kyctg-web.fullname" . }}-configmap
data:
  ASPNETCORE_ENVIRONMENT: {{ eq .Values.global.env.aspNetEnvironment "Production" | ternary "Production" "Staging"  }}
  production: {{ eq .Values.global.env.aspNetEnvironment "Production" | ternary "'true'" "'false'" }}
  staging: {{ eq .Values.global.env.aspNetEnvironment "Production" | ternary "'false'" "'true'" }}
  dev: "false"
  apiHostName: "{{ .Values.global.domains.api }}"
  keystone_clientId: "OregonTilth"
  keystone_issuer: "https://identity{{ eq .Values.global.env.aspNetEnvironment "Production" | ternary "" "-qa" }}.sitkatech.com"
  keystone_redirectUriRelative: "/login-callback"
  keystone_scope: "openid profile offline_access keystone"
  keystone_sessionCheckEnabled: "false"
  keystone_logoutUrl: "https://identity{{eq .Values.global.env.aspNetEnvironment "Production" | ternary "" "-qa" }}.sitkatech.com/account/logout"
  keystone_postLogoutRedirectUri: "/"
  keystone_waitForTokenInMsec: "500"
  keystone_responseType: "code"
  keystone_disablePKCE: "false"