apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kyctg-web.fullname" . }}
  labels:    
    tags.datadoghq.com/env: {{ .Values.global.env.name | quote }}
    tags.datadoghq.com/service: {{ include "kyctg-web.fullname" . }}
    tags.datadoghq.com/version: {{ .Values.image.tag | quote }}
    {{- include "kyctg-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kyctg-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        ad.datadoghq.com/tags: '{"teamName": "{{ .Values.namespace }}"}'
        rollme: {{ randAlphaNum 5 | quote }} # roll deployments on every upgrade: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kyctg-web.selectorLabels" . | nindent 8 }} 
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kyctg-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # this startup probe checks the app every 10 seconds to see if it's ready to receive traffic
          # it gives a very generous 5 minutes for the container to startup. As soon as it is successful
          # the liveness probe kicks into effect.
          startupProbe: 
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 4
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
          lifecycle:
            preStop:
              exec:
                command: ["sleep","120"]
          envFrom:
          - configMapRef:
              name: {{ include "kyctg-web.fullname" . }}-configmap
          # volumeMounts:
          # - name: secrets
          #   mountPath: /app/secrets
          #   readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 131
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
