services:
    oregontilth.api:
        image: oregontilth/api
        labels:
            - "com.microsoft.visualstudio.targetoperatingsystem=linux"
        build:
            args:
                source: ${DOCKER_BUILD_SOURCE}
        ports:
            - "8887:8080"
            - "8886:8081"
