apiVersion: v1
kind: Secret
metadata:
  name: kyctg-api-secrets
type: Opaque
stringData:
  apiSecrets: |
    {
      "DB_CONNECTION_STRING": "Data Source={{ .Values.global.env.dbServer }};Initial Catalog={{ .Values.global.env.databaseName }};Persist Security Info=True;User ID={{ .Values.global.env.sqlUsername }};Password={{ .Values.global.secrets.apiSqlPassword }}",
      "SendGridApiKey": "{{ .Values.global.secrets.sendGridApiKey }}",
    }