apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kyctg-api.fullname" . }}-configmap
data:
  SECRET_PATH: "/app/secrets/apiSecrets"
  DOCKER_BUILD_SOURCE: "."
  ASPNETCORE_ENVIRONMENT: "{{ .Values.global.env.aspNetEnvironment }}"
  SITKA_EMAIL_REDIRECT: "{{ .Values.global.env.emailRedirect }}"
  WEB_URL: "https://{{ .Values.global.domains.web }}"
  PlatformLongName: "Know Your Cost to Grow"