export enum FieldDefinitionTypeEnum {
    Name = 1,
    FieldLaborActivityForm = 2,
    MachineryCostForm = 3,
    FieldLaborTimeStudies = 4,
    CropForm = 5,
    CropUnitForm = 6,
    HarvestPostHarvestTimeStudies = 7,
    TPLaborActivityForm = 8,
    TPTrayTypeForm = 9,
    TPTimeStudies = 10,
    FieldLaborByCropForm = 11,
    FieldInputCostForm = 12,
    FieldInputByCropForm = 13,
    TPLaborByCropForm = 14,
    TPInputForm = 15,
    TPInputCostForm = 16,
    TPInfoForm = 17,
    GeneralFarmInfoForm = 18,
    CropSpecificInfoForm = 19,
    CropYieldInfoForm = 20,
    PreSeason = 21,
    TimeStudies = 22,
    PostSeason = 23,
    Results = 24,
	AverageHourlyWage = 25,
	StandardUnitOfSpaceLength = 26,
	StandardUnitOfSpaceWidth = 27,
    ResultsCropCropUnit = 28,
    ResultsCropCropUnitLaborHours = 29,
    ResultsCropCropUnitCostsPerCostCategory = 30

}