export enum FieldDefinitionTypeEnum {
    Name = 1,
    FieldLaborActivityForm = 2,
    MachineryCostForm = 3,
    FieldStandardTimesForm = 4,
    CropForm = 5,
    CropUnitForm = 6,
    HarvestPostHarvestStandardTimeForm = 7,
    TPLaborActivityForm = 8,
    TPTrayTypeForm = 9,
    TPStandardTimeForm = 10,
    FieldLaborByCropForm = 11,
    FieldInputCostForm = 12,
    FieldInputByCropForm = 13,
    TPLaborByCropForm = 14,
    TPInputForm = 15,
    TPInputCostForm = 16,
    TPInfoForm = 17,
    GeneralFarmInfoForm = 18,
    CropSpecificInfoForm = 19,
    CropYieldInfoForm = 20,
    PreSeason = 21,
    InSeason = 22,
    PostSeason = 23,
    Results = 24
}